services:
  - name: web
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT app:create_app
    envVars:
      - key: SECRET_KEY
        fromFile: .env
      - key: DATABASE_URL
        fromFile: .env

